apiVersion: v1
kind: Service
metadata:
    name: "{{ include "jupyter-pytorch.fullname" . }}"
spec:
    selector:
        app: "{{ include "jupyter-pytorch.fullname" . }}"
    type: ClusterIP
    ports:
    - name: jupyter-service
      port: 8888
      targetPort: jupyter
      